version: '3'
services:
  task-api:
    env_file:
      - dev-variables.env
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:5000"
    volumes:
      - .:/app      